# Generated by Django 4.0.1 on 2022-01-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('year', models.EmailField(max_length=30)),
                ('hobbies', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
