# Generated by Django 4.0.1 on 2022-01-06 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='email',
            new_name='experiance',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='dob',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='passwd',
            new_name='username',
        ),
    ]
