# Generated by Django 4.0.1 on 2022-01-06 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_email_new_experiance_rename_dob_new_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='year',
        ),
    ]
