# Generated by Django 4.0 on 2021-12-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='passwd',
            new_name='password',
        ),
    ]
