# Generated by Django 4.0 on 2021-12-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_new1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new1',
            name='email',
        ),
    ]
