# Generated by Django 4.0.1 on 2022-01-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='idnew',
            new_name='id_new',
        ),
    ]
