# Generated by Django 4.0.1 on 2022-01-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addmore1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('psw1', models.CharField(max_length=20)),
                ('psw2', models.CharField(default='', max_length=20)),
                ('interest', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
